#!/usr/bin/python3

import sys, re, time, json
from SWDCommon import *
from SWDErrors import *
from Kinetis import *
from FlashProgrammer import *

def find_adapter(name):
    mod = __import__(name)
    return mod.Adapter()

USAGE = "Usage: {0} <adapter name> <device name> <path to hex file>"

def main():
    if len(sys.argv) != 4:
        print(USAGE.format(sys.argv[0]))
        return
    adapter = find_adapter(sys.argv[1])
    try:
        debugPort = DebugPort(adapter)
        debugPort.init()
        dev = Kinetis(debugPort)
        prog = FlashProgrammer(dev, sys.argv[2])
        prog.program(sys.argv[3])
    except SWDFaultError as e:
        status = debugPort.status()
        print("Error! DP Status: {0:x}".format(debugPort.status()))
        debugPort.abort(status & 0x1, status & 0x80, status & 0x20, status & 0x10, 0, debug=True)

if __name__ == "__main__":
    main()
